FEAT: 유저 생성 기능/유저 수정 기능 작성 #3
f-lab-edu/f-market pull request #4
Opened 2024-11-30 13:59 UTC by sorryisme

FEAT: 회원 수정 기능 추가

## #️⃣연관된 이슈
#3 

> ex) #이슈번호, #이슈번호

## 📝작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명해주세요

1. 공통 Response 작성
- API 명세에 작성한 기준으로 공통 응답 객체 작성 
https://github.com/f-lab-edu/f-market/wiki/API-%EB%AA%85%EC%84%B8

2. 커스텀 Exception 작성
- 커스텀 Exception 작성
- RestControllerAdvice 적용

4. 유효성 검토 추가
- 스프링 유효성 검토 애노테이션을 통해서 기본적인 DTO를 통한 유효성 검토 추가

5. 회원 관련 기능 추가 및 테스트 코드 작성
- 개인 회원가입 
- 개인 회원 정보 수정
- 셀러 회원가입 추가

6. 기타 
 - 카테고리 초기화 데이터 추가 => data.sql 파일 작성
 - 비밀번호 암호화 유틸 작성

2024-12-02 08:25 UTC, f-lab-joseph commented
초기작업이라 큰 범위로 PR 이 올라왔는데 .. PR 은 작게 잘라서 작업해주시면 좋겠습니다.

2024-12-02 08:26 UTC, f-lab-joseph approved these changes

2024-12-02 08:26 UTC, f-lab-joseph commented on src/test/groovy/com/sorryisme/fmarket/service/UserServiceTest.groovy
> +        UserService userService = new UserService(userMapper)
매번 만들지 말고 멤버로 선언하면 어떤가요 ?

2024-12-03 13:59 UTC, f-lab-joseph requested changes
test

2024-12-03 14:00 UTC, f-lab-joseph approved these changes

2024-12-03 14:21 UTC, sorryisme commented on src/test/groovy/com/sorryisme/fmarket/service/UserServiceTest.groovy
> +        UserService userService = new UserService(userMapper)
네 다음 PR에 적용하겠습니다

2024-12-03 14:21 UTC, merged